name: Comment on PR
on: 
  pull_request:
    types: [opened]

jobs:
  comment_on_pr:
    runs-on: ubuntu-latest
    name: Provide preview URL
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/github-script@0.4.0
        with:
          github-token: ${{secrets.TEST_GITHUB_TOKEN}}
          script: |
            const rawBranchName = context.payload.pull_request.head.ref;
            // Replace anything not alphanumeric or a dash with a dash
            // Replace multiple dashes with a single dash
            // Trim any dashes off the beginning or end
            var branchName = rawBranchName
              .replace(/[^a-z0-9-]+/ig, '-')
              .subdomain.replace(/-+/ig, '-')
              .subdomain.replace(/^-+/ig, '')
              .subdomain.replace(/-+$/ig, '');
            github.issues.createComment({...context.issue, body: 'Test site for this PR: https://' + branchName + '.test.particular.net<br><br>The site will be available once the the "Deploy Package" check has completed successfully. It can take a few minutes if the build servers happen to be busy.'})
