name: Comment on PR
on: 
  pull_request:
    types: [opened]

jobs:
  comment_on_pr:
    runs-on: ubuntu-latest
    name: Provide preview URL
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/github-script@0.3.0
        with:
          github-token: ${{secrets.TEST_GITHUB_TOKEN}}
          script: |
            github.issues.createComment({...context.issue, body: 'Test site for this PR: https://' + context.payload.pull_request.head.ref + '.test.particular.net<br><br>The site will be available once the the "Deploy Package" check has completed successfully. It can take a few minutes if the build servers happen to be busy.'})
